services:
  - type: web
    name: image-uploader
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: UPLOAD_PASSPHRASE
        sync: false
      - key: ALLOWED_FILE_EXTENSIONS
        sync: false
      # - key: DROPBOX_TOKEN
      #   sync: false
